GOOD_JOB = ['That’s great',
            'Good job',
            'Excellent',
            'I appreciate that',
            'That’s looking good',
            'Good work',
            'Great work',
            'You’re doing well',
            'Good to have you on the team',
            'You made the difference',
            'Exceptional',
            'Thanks for the extra',
            'Wonderful',
            'That is so significant',
            'Superb',
            'Perfect',
            'Just what was needed',
            'Centre button',
            'A significant contribution',
            'Wow',
            'Fantastic',
            'Thanks you',
            'Just what the doctor ordered',
            'First class',
            'Nice job',
            'Way to go',
            'Far out',
            'Just the ticket',
            'You are a legend',
            'Very professional',
            'Where would we be without you',
            'Brilliant',
            'Top marks',
            'Impressive',
            'You hit the target',
            'Neat',
            'Cool',
            'Bullseye',
            'How did you get so good',
            'Beautiful',
            'Just what was wanted',
            'Right on the money',
            'Great',
            'Just right',
            'Congratulations',
            'Very skilled',
            'I’m glad you’re on my team',
            'It is good to work with you',
            'You did us proud',
            'This is going to make us shine',
            'Well done',
            'I just love it',
            'You are fantastic',
            'Great job',
            'Professional as usual',
            'You take the biscuit every time',
            'I’m proud of you',
            'Don’t ever leave us',
            'Are you good or what?',
            'The stuff of champions',
            'Cracking job',
            'First class job',
            'Magnificent',
            'Bravo',
            'Amazing',
            'Simply superb',
            'Triple A',
            'Perfection',
            'Poetry in motion',
            'Sheer class',
            'World class',
            'Polished performance',
            'Class act',
            'Unbelievable',
            'Gold plated',
            'Just classic',
            'Super',
            'Now you’re cooking',
            'You are so good',
            'You deserve a pat on the back',
            'Tremendous job',
            'Unreal',
            'Treasure',
            'Crash hot',
            'You beauty',
            'The cat’s whiskers',
            'I just can’t thank you enough',
            'You always amaze me',
            'Magic',
            'Another miracle',
            'Terrific',
            'What a star',
            'Colossal',
            'Wonderful',
            'Top form',
            'You’re one of a kind',
            'Unique',
            'Way out',
            'Incredible',
            'Ace']
